wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1677084470.306963
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 77
      3:
      - 7
      - 16
      - 23
      - 24
      4: 3.10.8
      5: 0.13.9
      8:
      - 8
dataset:
  desc: null
  value:
    abs_thr: null
    atlas: aal
    data_path: /mnt/workspace/graph_NN/neurograph/datasets
    data_type: graph
    experiment_type: fmri
    feature_type: conn_profile
    name: cobre
    pt_thr: null
log:
  desc: null
  value:
    test_step: 1
    wandb_mode: null
    wandb_name: null
    wandb_project: mri_gnn_2
model:
  desc: null
  value:
    data_type: graph
    dropout: 0.2
    final_node_dim: 32
    hidden_dim: 32
    layer_module: GCNConv
    mlp_config:
      act_func: null
      act_func_params: null
      in_size: null
      layers: []
      out_size: null
    n_classes: 2
    name: baseGNN
    num_heads: 2
    num_layers: 1
    pooling: mean
    use_abs_weight: true
    use_batchnorm: true
    use_weighted_edges: false
seed:
  desc: null
  value: 1380
train:
  desc: null
  value:
    batch_size: 8
    device: cuda
    epochs: 20
    loss: CrossEntropyLoss
    loss_args:
      reduction: sum
    optim: Adam
    optim_args:
      lr: 0.001
      weight_decay: 0.0001
    prob_thr: 0.5
    scheduler: null
    scheduler_args:
      factor: 0.1
      patience: 5
      verbose: true
    scheduler_metric: loss
    select_best_metric: loss
    valid_batch_size: 8
